stages:
  - build
  - tests

build:
  stage: build 
  script:
    # - docker system prune -f
    - docker run --rm -v %cd%:/opt/project -w="/opt/project" python:2.7.15 /bin/bash -c "python -m pip install -r requirements.txt && python -m pip install -r test-requirements.txt"' 
  tags:
    - words

tests:
  stage: tests  
  script: 
    - mkdir Settings
    - echo "{""AppSid"":""$env:AppSid"",""AppKey"":""$env:AppKey"",""BaseUrl"":""$env:TestServerUrl"" }" > Settings/servercreds.json
    - docker run --rm -v %cd%:/opt/project -w="/opt/project" python:2.7.15 /bin/bash "nosetests --with-xunit"
  dependencies:
    - build
  artifacts:
    paths:       
      - 'nodesets.xml'   
    reports: 
      junit: 
        - 'nodesets.xml'   
  tags:
    - words