stages:
  - build
  - tests

build:
  stage: build 
  script:
    # - docker system prune -f
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:2.7.15 bash scripts/build.sh
  tags:
    - awcloud-linux

tests:
  stage: tests  
  script: 
    - mkdir -p Settings
    - echo "{""AppSid"":""$env:AppSid"",""AppKey"":""$env:AppKey"",""BaseUrl"":""$env:TestServerUrl"" }" > Settings/servercreds.json
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:2.7.15 bash scripts/build.sh
    - docker run --rm -v $PWD:/opt/project -w="/opt/project" python:2.7.15 bash -c "nosetests --with-xunit"
  dependencies:
    - build
  artifacts:
    paths:       
      - 'nodesets.xml'   
    reports: 
      junit: 
        - 'nodesets.xml'   
  tags:
    - awcloud-linux