stages:
  - build&test
  - wait-for-publish
  - merge-to-testPackage
  - publish-test
  - test-package

.tests:
  stage: build&test  
  script: 
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:2.7.15 bash scripts/build.sh
    - ls -l
  artifacts:
    paths:       
      - 'nosetests.xml'  
      - 'lintResults.txt' 
    reports: 
      junit: 
        - 'nosetests.xml'
  tags:
    - awcloud-linux

wait-for-publish:
  stage: wait-for-publish
  when: manual
  script:
    - echo 'Starting publishing process'
  tags:
    - awcloud-linux

merge-to-test:
  stage: merge-to-testPackage
  before_script:
    - $env:ORIGIN += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-python.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
    - $env:SDK_VERSION += ((Get-Date).AddMonths(1)).tostring("yy.M")
  script: 
    - git checkout CI
    - 'git remote set-url origin $env:ORIGIN'
    - git checkout testPackageNew
    - git reset --hard origin/testPackageNew
    - git merge --no-ff --allow-unrelated-histories origin/CI
    - git diff --name-status
    - git push
  dependencies:
    - wait-for-publish
  only: 
    - CI
  tags: 
    - awcloud

publish-test:
  stage: publish-test
  script:
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:3.6 bash scripts/publish.sh $PypiLogin $PypiPass
  artifacts:
    paths:       
      - '.pypirc'  
  only:
    - testPackageNew
  tags:
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"Base
    - awcloud-linux
  dependencies:
    - wait-for-publish
    - merge-to-testPackage

test-package:
  stage: test-package
  script: 
    - python -m pip install --upgrade setuptools wheel
    - pip install urllib3
    - pip install --index-url https://test.pypi.org/simple/ asposewordscloud
    - python -m pip install -r requirements.txt && python -m pip install -r test-requirements.txt
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - nosetests --with-xunit
  tags: 
    - awcloud-linux
  artifacts:
    paths:
      - nosetests.xml
    reports:
      junit:
        - nosetests.xml
  dependencies:
    - wait-for-publish
    - merge-to-testPackage
    - publish-test


  
