stages:
  - build&test
  - merge-to-testPackage
  - publish

.tests:
  stage: build&test  
  script: 
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - docker run --rm -v $PWD:/opt/project -w=/opt/project python:2.7.15 bash scripts/build.sh
    - ls -l
  artifacts:
    paths:       
      - 'nosetests.xml'  
      - 'lintResults.txt' 
    reports: 
      junit: 
        - 'nosetests.xml'
  tags:
    - awcloud-linux

merge-to-test:
  stage: merge-to-testPackage
  before_script:
    - export ORIGIN="https://$GIT_CI_USER:$GIT_CI_PASS@git.auckland.dynabic.com/words-cloud/words-cloud-python.git -f"
    - export SDK_VERSION='date +%y.%m'
  script: 
    - git checkout --merge testPackageNew
    - git reset --hard origin/testPackageNew
    - git merge --no-ff --allow-unrelated-histories origin/CI
    - git diff --name-status
    - git commit -am "Merged CI branch to testPackageNew"
    - git push $ORIGIN
    # - docker run --rm -v $PWD:/opt/project -w=/opt/project python:3.6 bash scripts/publish.sh $PypiLogin $PypiPass
  tags: 
    - awcloud-linux

  
